COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src
COMPONENT_REQUIRES := ESPressio_Threads ESPressio_Observable ESPressio_Timing

CXXFLAGS += -DESPRESSIO_EVENT
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_MAJOR=6
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_MINOR=0
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_PATCH=3
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_STRING=\"6.0.3\"

CXXFLAGS += -std=gnu++17
